/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade04.view;

import javax.swing.JOptionPane;


/**
 *
 * @author eduardo
 */
public class TelaAdivinhador extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaAdivinhador.class.getName());

    /**
     * Creates new form TelaAdivinhador
     */
    public TelaAdivinhador() {
        initComponents();
        lblTextoA.setText("<html>Escolha um numero <br> de 1 a 5</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAkinatorImage = new javax.swing.JLabel();
        lblTextoA = new javax.swing.JLabel();
        lblBalaoDeFala = new javax.swing.JLabel();
        btnPalpite = new javax.swing.JButton();
        txtNumeroRecebido = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAkinatorImage.setIcon(new javax.swing.ImageIcon("/home/eduardo/Documentos/GitHub/prg03eduardonascimentosantos/prg03eduardonascimentosantos/src/main/java/br/com/ifba/atividade04/images/kindpng_4647402.png")); // NOI18N
        getContentPane().add(lblAkinatorImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        lblTextoA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextoA.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblTextoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 140, 70));

        lblBalaoDeFala.setIcon(new javax.swing.ImageIcon("/home/eduardo/Documentos/GitHub/prg03eduardonascimentosantos/prg03eduardonascimentosantos/src/main/java/br/com/ifba/atividade04/images/balao-de-fala.png")); // NOI18N
        getContentPane().add(lblBalaoDeFala, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, 142));

        btnPalpite.setText("Palpite");
        btnPalpite.addActionListener(this::btnPalpiteActionPerformed);
        getContentPane().add(btnPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 110, 50));

        txtNumeroRecebido.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(txtNumeroRecebido, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 110, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalpiteActionPerformed
        int valorRecebido = Integer.parseInt(txtNumeroRecebido.getValue().toString());
        int aleatorio = (int) (Math.random() * 5) + 1; // Loop de 1 a 5
        
            if (valorRecebido > 5 || valorRecebido < 1){
            JOptionPane.showMessageDialog(this, "Esse valor NAO está entre 1 e 5"); //mensagem de erro
            }
        
            if (valorRecebido == aleatorio){
                lblTextoA.setText("Parabéns, você acertou");
            }else{
            lblTextoA.setText("Este não é o valor correto");
            }
        
    }//GEN-LAST:event_btnPalpiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaAdivinhador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPalpite;
    private javax.swing.JLabel lblAkinatorImage;
    private javax.swing.JLabel lblBalaoDeFala;
    private javax.swing.JLabel lblTextoA;
    private javax.swing.JSpinner txtNumeroRecebido;
    // End of variables declaration//GEN-END:variables
}
